### ISSUE TITLE
Spec on options asserts making optional arguments forced to be present

### ISSUE THREAD

**Issue by gaberger** [l3nz/cli-matic#105]
any

[ Please specify which version of cli-matic you're using.]

JVM

[ Please specify which platform you are using cli-matic on, like JVM or JS and which version ]

When applying :spec on option forces option to be always present as the assert fails when empty. Should this be only applied when :default is set or :default present?

[ Please provide a short and to the point description of the problem ]

**repro**

[ Please provide a minimal working reproduction of the problem ]

**expected behavior**

[ What is the behavior you expected to see from clj-matic? Please provide a minimal working example ]

**actual behavior**

[ What is the actual behavior of clj-matic? ]

**Comment by l3nz** [comment]
Fixed in upcoming 0.4.2
