### ISSUE TITLE
Printing on STDERR in Planck

### ISSUE THREAD

**Issue by l3nz** [l3nz/cli-matic#111]
**version**

0.4.0, CLJS

**problem**

It would be great if we were to print everything on STDERR in Planck too afte the changs made for bug #100  - I made the changes to the platforms namespace, but I was not able to print our own messages to STDERR.

**expected behavior**

             ./toycalc.cljs 2> /dev/null

should not output anything.

**Comment by l3nz** [comment]
See https://github.com/l3nz/cli-matic/blob/6c3f46b429da93754ad3d6fc455fbeb90012cba7/src/cli_matic/platform.cljs#L109

**Comment by mfikes** [comment]
I think this might work:

```
(defn printError [o]
   (binding [*print-fn* *print-err-fn*]
     (println o)))
```

**Comment by l3nz** [comment]
Thanks @mfikes - works like a charm!
