### ISSUE TITLE
[Ftr] Flag to not run System/Exit

### ISSUE THREAD

**Issue by lgrapenthin** [l3nz/cli-matic#144]
**Is your feature request related to a problem? Please describe.**
I want to see what it prints, not just return value of run-cmd*

**Describe the solution you'd like**
A flag to run-cmd or a variation of run-cmd that doesn't call System/Exit

**Describe alternatives you've considered**
Not using this lib

**Comment by lgrapenthin** [comment]
Workaround
```
(alter-var-root #'cli-matic.platform/exit-script
                  (constantly
                   (fn [retval]
                     (println "cli-matic would shut down with" retval))))
```

**Comment by l3nz** [comment]
> **Describe the solution you'd like** A flag to run-cmd or a variation of run-cmd that doesn't call System/Exit

I see, but **why**?

**Comment by lgrapenthin** [comment]
> I want to see what it prints, not just return value of run-cmd*

Needless to add, I prefer not restarting my JVM during development.

**Comment by l3nz** [comment]
I think your workaround is perfect then.
