### ISSUE TITLE
[Ftr] Ability to *disable* -? gloabl help

### ISSUE THREAD

**Issue by mtwomey** [l3nz/cli-matic#158]
The '-?' version of help doesn't work on mac in zsh without escaping it:

-? returns `zsh: no matches found: -?`

-\\? works correctly. I'd prefer to just have the whole global help line disabled:

`   -?, --help`

Is this possible?

As a follow-on to this, if `GLOBAL OPTIONS:` is now empty (because there were no other options), it should also not be displayed.

**Comment by l3nz** [comment]
Not sure how you could do that selectively based on zsh - because -h could be a "native"  option (`-h 127.0.0.1`) so we cannot just use that.

I have a mac too and I feel your pain. I love zsh but `-?` drives me nuts.
