### ISSUE TITLE
Returning lazy sequences from :runs throws - IPending is not IDeref

### ISSUE THREAD

**Issue by NoahTheDuke** [l3nz/cli-matic#161]
**Problem**

In a subcommand `:runs`, functions that return lazy sequences throw. This includes functions like `map` and `lazy-seq`. Simplest example I could come up with:

```clojure
(fn [& _] (lazy-seq (cons 1 ())))
```

This is because `cli-matic.platform/isJvmPromise?` checks if the returned value is an instance of `IPending`, which is used for realizing values, not for dereferencing (delivering, completing, calculating) values.

**Repro**

```clojure
(let [cmd (fn [& _] (lazy-seq (cons 1 ())))
      setup {:command     "ipending-example"
             :opts        []
             :subcommands [{:command "foo"
                            :opts    []
                            :runs    cmd}]}]
  (run-cmd* setup ["foo"]))
```

**Expected vs actual behavior**

Should not throw, should default to 0.

**Version / Platform**

cli-matic 0.5.4, JVM 11, Clojure 1.11.1

**Comment by l3nz** [comment]
You are right. Merged.
