### ISSUE TITLE
Support nil options on sub-command

### ISSUE THREAD

**Issue by gaberger** [l3nz/cli-matic#24]
I would like the option of executing a sub-command that does not take any options. the use-case might be just to query information.

**Comment by l3nz** [comment]
You are right, this is something I often do myself. 😄 

Anyway, if you have something like:

```
{:app         {:command     "...."
                 :description "...."
                 :version     "180504.1"}

   :global-opts []

   :commands    [
                  {:command     "noparms"
                  :description "This is a command without parameters"
                  :opts        []
                  :runs        cmd_types}]})
```

it works with the current version (you need to have an empty vector, and cannot skip the `:opts`, by design).

Hope you will enjoy CLI-matic!
