### ISSUE TITLE
Support nil options on sub-command

### ISSUE THREAD

**Issue by suryaaditya** [l3nz/cli-matic#65]
issue #24 is not working in current release, ability to use empty :opts [].

**Comment by l3nz** [comment]
It works for me: https://github.com/l3nz/cli-matic/blob/master/examples/noparms.clj

**Comment by suryaaditya** [comment]
It does not work if I have zero argument function, in your example the function 'say_hi' takes argument 'parms' and does not do anything with it. If and make it as function that takes no arugment it fails with the exception:

```
clojure.lang.ArityException
   :message Wrong number of args (1) passed to:

```
```
(defn say_hi
  "Just say hi"
  [parms]
  (println "Hi man!"))
```

**Comment by l3nz** [comment]
This is by design; all functions called will receive a map with parsed arguments and any leftovers. All of them expect a one-arity call.
