### ISSUE TITLE
Why does GLOBAL OPTIONS help disappear on sub-commands?

### ISSUE THREAD

**Issue by gaberger** [l3nz/cli-matic#76]
0.3.8

[ Please specify which version of cli-matic you're using.]

JVM, GraalVM

[ Please specify which platform you are using clj-matic on, like JVM or JS and which version ]

Why does GLOBAL OPTIONS disappear on sub-option --help

[ Please provide a short and to the point description of the problem ]

**repro**

[ Please provide a minimal working reproduction of the problem ]

**expected behavior**

[ What is the behavior you expected to see from clj-matic? Please provide a minimal working example ]

**actual behavior**

[ What is the actual behavior of clj-matic? ]

**Comment by l3nz** [comment]
This is expected, as not to make it too big.
