### ISSUE TITLE
[Ftr] Support multi-line for option :as

### ISSUE THREAD

**Issue by lread** [l3nz/cli-matic#94]
**Is your feature request related to a problem? Please describe.**
When using cli-matic, I sometimes have options that deserve a few lines of description.
The `:as` for an option is currently single line.

**Describe the solution you'd like**
Follow the same scheme used for `:description` as used in`:app` and `:command` which allows for a single string or a vector of strings, each string representing a line.

Multi-line `:as` text would automatically be indented appropriately by cli-matic.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by lread** [comment]
If this makes sense to folks, I can work on a PR.

**Comment by l3nz** [comment]
Definitely :)

**Comment by l3nz** [comment]
In the end I did not accept your PR but based my work on your "Allow multiline values for :as in options via customized :summary-fn" #96 where you did all the heavy lifting and I did some copy-and -paste 

Sorry it took so long but until 0.4.0 was out I did not want to make changes to the core. Now thatt it's done we got space for improving things.
